spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: admin 
            username: admin
            password: admin
# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port